import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const docsCopyPageContent = {
  content: {
    copyPage: t({
      en: "Copy Page",
      es: "Copiar página",
      fr: "Copier la page",
      ja: "ページをコピー",
      ko: "페이지 복사",
      pt: "Copiar página",
      "zh-CN": "复制页面",
    }),
    openInChatGpt: t({
      en: "Open in ChatGPT",
      es: "Abrir en ChatGPT",
      fr: "Ouvrir dans ChatGPT",
      ja: "ChatGPT で開く",
      ko: "ChatGPT에서 열기",
      pt: "Abrir no ChatGPT",
      "zh-CN": "在 ChatGPT 中打开",
    }),
    openInClaude: t({
      en: "Open in Claude",
      es: "Abrir en Claude",
      fr: "Ouvrir dans Claude",
      ja: "Claude で開く",
      ko: "Claude에서 열기",
      pt: "Abrir no Claude",
      "zh-CN": "在 Claude 中打开",
    }),
    openInCursor: t({
      en: "Open in Cursor",
      es: "Abrir en Cursor",
      fr: "Ouvrir dans Cursor",
      ja: "Cursor で開く",
      ko: "Cursor에서 열기",
      pt: "Abrir no Cursor",
      "zh-CN": "在 Cursor 中打开",
    }),
    openInGemini: t({
      en: "Open in Gemini",
      es: "Abrir en Gemini",
      fr: "Ouvrir dans Gemini",
      ja: "Gemini で開く",
      ko: "Gemini에서 열기",
      pt: "Abrir no Gemini",
      "zh-CN": "在 Gemini 中打开",
    }),
    openInGrok: t({
      en: "Open in Grok",
      es: "Abrir en Grok",
      fr: "Ouvrir dans Grok",
      ja: "Grok で開く",
      ko: "Grok에서 열기",
      pt: "Abrir no Grok",
      "zh-CN": "在 Grok 中打开",
    }),
    openInPerplexity: t({
      en: "Open in Perplexity",
      es: "Abrir en Perplexity",
      fr: "Ouvrir dans Perplexity",
      ja: "Perplexity で開く",
      ko: "Perplexity에서 열기",
      pt: "Abrir no Perplexity",
      "zh-CN": "在 Perplexity 中打开",
    }),
    openInScira: t({
      en: "Open in Scira AI",
      es: "Abrir en Scira AI",
      fr: "Ouvrir dans Scira AI",
      ja: "Scira AI で開く",
      ko: "Scira AI에서 열기",
      pt: "Abrir no Scira AI",
      "zh-CN": "在 Scira AI 中打开",
    }),
    openInV0: t({
      en: "Open in v0",
      es: "Abrir en v0",
      fr: "Ouvrir dans v0",
      ja: "v0 で開く",
      ko: "v0에서 열기",
      pt: "Abrir no v0",
      "zh-CN": "在 v0 中打开",
    }),
    viewAsMarkdown: t({
      en: "View as Markdown",
      es: "Ver como Markdown",
      fr: "Afficher en Markdown",
      ja: "Markdown で表示",
      ko: "Markdown으로 보기",
      pt: "Ver como Markdown",
      "zh-CN": "以 Markdown 查看",
    }),
  },
  key: "docs-copy-page",
} satisfies Dictionary;

export default docsCopyPageContent;
