import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const homePdfPreviewContent = {
  content: {
    alertDescription: t({
      en: "A callout block for warnings, notes, and important information.",
      es: "Un bloque de llamada para advertencias, notas e información importante.",
      fr: "Un bloc d'appel pour les avertissements, notes et informations importantes.",
      ja: "警告、注記、重要な情報のためのコールアウトブロック。",
      ko: "경고, 메모 및 중요한 정보를 위한 콜아웃 블록.",
      pt: "Um bloco de destaque para avisos, notas e informações importantes.",
      "zh-CN": "用于警告、备注和重要信息的提示块。",
    }),
    badgeDescription: t({
      en: "A styled label for status indicators, tags, and inline annotations.",
      es: "Una etiqueta con estilo para indicadores de estado, etiquetas y anotaciones en línea.",
      fr: "Un libellé stylisé pour les indicateurs de statut, les étiquettes et les annotations en ligne.",
      ja: "ステータスインジケーター、タグ、インライン注釈のためのスタイル付きラベル。",
      ko: "상태 표시기, 태그 및 인라인 주석을 위한 스타일된 레이블.",
      pt: "Um rótulo estilizado para indicadores de status, tags e anotações em linha.",
      "zh-CN": "用于状态指示器、标签和内联注释的样式化标签。",
    }),
    cardDescription: t({
      en: "A contained layout for grouping related content with border and padding.",
      es: "Un diseño contenedor para agrupar contenido relacionado con borde y relleno.",
      fr: "Un agencement conteneur pour regrouper le contenu associé avec bordure et marge intérieure.",
      ja: "関連コンテンツをグループ化するためのボーダーとパディング付きのコンテナレイアウト。",
      ko: "관련 콘텐츠를 그룹화하기 위한 테두리와 패딩이 있는 컨테이너 레이아웃.",
      pt: "Um layout contêiner para agrupar conteúdo relacionado com borda e preenchimento.",
      "zh-CN": "用于将相关内组合在一起的带边框和内边距的容器布局。",
    }),
    corporateInvoiceDescription: t({
      en: "Production-ready document layouts for invoices, reports, and more — built with composable components.",
      es: "Diseños de documentos listos para producción para facturas, informes y más — construidos con componentes componibles.",
      fr: "Dispositions de documents prêtes pour la production pour factures, rapports et plus — construites avec des composants composites.",
      ja: "請求書、レポートなどに対応する本番環境向けドキュメントレイアウト — 合成可能なコンポーネントで構築。",
      ko: "청구서, 보고서 등을 위한 프로덕션 준비 완료 문서 레이아웃 — 합성 가능한 컴포넌트로 구축.",
      pt: "Layouts de documentos prontos para produção para faturas, relatórios e mais — construídos com componentes composáveis.",
      "zh-CN": "用于发票、报告等的生产就绪文档布局——使用可组合组件构建。",
    }),
    corporateInvoiceEyebrow: t({
      en: "The document drop · 01",
      es: "La caída de documentos · 01",
      fr: "La sortie document · 01",
      ja: "ドキュメントドロップ · 01",
      ko: "문서 드롭 · 01",
      pt: "A queda de documentos · 01",
      "zh-CN": "文档发布 · 01",
    }),
    corporateInvoiceHeading: t({
      en: "Build PDFs at component speed.",
      es: "Construye PDFs a la velocidad de los componentes.",
      fr: "Construisez des PDF à la vitesse des composants.",
      ja: "コンポーネントの速度で PDF を構築。",
      ko: "컴포넌트 속도로 PDF를 구축하세요.",
      pt: "Construa PDFs na velocidade dos componentes.",
      "zh-CN": "以组件速度构建 PDF。",
    }),
    corporateInvoiceName: t({
      en: "Corporate invoice",
      es: "Factura corporativa",
      fr: "Facture d'entreprise",
      ja: "法人請求書",
      ko: "법인 청구서",
      pt: "Fatura corporativa",
      "zh-CN": "企业发票",
    }),
    dataTableDescription: t({
      en: "A full-featured data table with sorting, pagination, and cell formatting.",
      es: "Una tabla de datos completa con ordenación, paginación y formato de celdas.",
      fr: "Un tableau de données complet avec tri, pagination et formatage des cellules.",
      ja: "ソート、ページネーション、セルフォーマット機能を備えたフル機能データテーブル。",
      ko: "정렬, 페이지 매기기 및 셀 서식 지정 기능이 완비된 데이터 테이블.",
      pt: "Uma tabela de dados completa com ordenação, paginação e formatação de células.",
      "zh-CN": "功能齐全的数据表，支持排序、分页和单元格格式化。",
    }),
    dividerDescription: t({
      en: "A visual separator with configurable color, thickness, and margin.",
      es: "Un separador visual con color, grosor y margen configurables.",
      fr: "Un séparateur visuel avec couleur, épaisseur et marge configurables.",
      ja: "色、太さ、マージンを設定可能なビジュアルセパレーター。",
      ko: "색상, 두께 및 여백을 구성할 수 있는 시각적 구분선.",
      pt: "Um separador visual com cor, espessura e margem configuráveis.",
      "zh-CN": "具有可配置颜色、粗细和边距的视觉分隔符。",
    }),
    financialReportDescription: t({
      en: "Start with a component, make it yours, and render confidently. Everything you need is ready.",
      es: "Comienza con un componente, hazlo tuyo y renderiza con confianza. Todo lo que necesitas está listo.",
      fr: "Commencez avec un composant, faites-le vôtre et rendez en toute confiance. Tout ce dont vous avez besoin est prêt.",
      ja: "コンポーネントから始めて、自分だけのものにし、自信を持ってレンダリング。必要なものはすべて準備完了。",
      ko: "컴포넌트로 시작하여 나만의 것으로 만들고 자신 있게 렌더링하세요. 필요한 모든 것이 준비되어 있습니다.",
      pt: "Comece com um componente, faça o seu e renderize com confiança. Tudo o que você precisa está pronto.",
      "zh-CN":
        "从一个组件开始，使其成为你的，自信地渲染。您所需的一切都已准备就绪。",
    }),
    financialReportEyebrow: t({
      en: "Financial overview",
      es: "Resumen financiero",
      fr: "Aperçu financier",
      ja: "財務概要",
      ko: "재무 개요",
      pt: "Visão geral financeira",
      "zh-CN": "财务概览",
    }),
    financialReportHeading: t({
      en: "Your PDF workspace is ready.",
      es: "Su espacio de trabajo PDF está listo.",
      fr: "Votre espace de travail PDF est prêt.",
      ja: "PDF ワークスペースの準備ができました。",
      ko: "PDF 작업 공간이 준비되었습니다.",
      pt: "Seu espaço de trabalho PDF está pronto.",
      "zh-CN": "您的 PDF 工作区已准备就绪。",
    }),
    financialReportName: t({
      en: "Financial report",
      es: "Informe financiero",
      fr: "Rapport financier",
      ja: "財務レポート",
      ko: "재무 보고서",
      pt: "Relatório financeiro",
      "zh-CN": "财务报告",
    }),
    graphDescription: t({
      en: "A data visualization component for charts and statistical graphics.",
      es: "Un componente de visualización de datos para gráficos y gráficos estadísticos.",
      fr: "Un composant de visualisation de données pour les graphiques et les graphiques statistiques.",
      ja: "チャートと統計グラフィックスのためのデータ可視化コンポーネント。",
      ko: "차트 및 통계 그래픽을 위한 데이터 시각화 컴포넌트.",
      pt: "Um componente de visualização de dados para gráficos e gráficos estatísticos.",
      "zh-CN": "用于图表和统计图形的数据可视化组件。",
    }),
    imageDescription: t({
      en: "An image component optimized for PDF rendering with aspect ratio and sizing.",
      es: "Un componente de imagen optimizado para la renderización de PDF con relación de aspecto y tamaño.",
      fr: "Un composant d'image optimisé pour le rendu PDF avec rapport d'aspect et dimensionnement.",
      ja: "アスペクト比とサイズ設定に最適化された PDF レンダリング用画像コンポーネント。",
      ko: "종횡비 및 크기 조정에 최적화된 PDF 렌더링용 이미지 컴포넌트.",
      pt: "Um componente de imagem otimizado para renderização de PDF com proporção e dimensionamento.",
      "zh-CN": "针对 PDF 渲染优化的图像组件，支持宽高比和尺寸设置。",
    }),
    keyValueDescription: t({
      en: "A flexible key-value layout for metadata, summaries, and label pairs.",
      es: "Un diseño flexible de clave-valor para metadatos, resúmenes y pares de etiquetas.",
      fr: "Un agencement clé-valeur flexible pour les métadonnées, résumés et paires d'étiquettes.",
      ja: "メタデータ、要約、ラベルペアのための柔軟なキー値レイアウト。",
      ko: "메타데이터, 요약 및 레이블 쌍을 위한 유연한 키-값 레이아웃.",
      pt: "Um layout chave-valor flexível para metadados, resumos e pares de rótulos.",
      "zh-CN": "用于元数据、摘要和标签对的灵活键值布局。",
    }),
    listDescription: t({
      en: "An ordered or unordered list with custom markers and nested items.",
      es: "Una lista ordenada o desordenada con marcadores personalizados y elementos anidados.",
      fr: "Une liste ordonnée ou non ordonnée avec des marqueurs personnalisés et des éléments imbriqués.",
      ja: "カスタムマーカーとネストされたアイテムを含む有序リストまたは無序リスト。",
      ko: "사용자 지정 마커와 중첩 항목이 있는 순서 목록 또는 비순서 목록.",
      pt: "Uma lista ordenada ou não ordenada com marcadores personalizados e itens aninhados.",
      "zh-CN": "带有自定义标记和嵌套项目的有序或无序列表。",
    }),
    minimalInvoiceDescription: t({
      en: "A clean, minimal invoice layout with essential billing details and payment terms.",
      es: "Un diseño de factura limpio y minimalista con detalles de facturación esenciales y términos de pago.",
      fr: "Un agencement de facture propre et minimaliste avec les détails de facturation essentiels et les conditions de paiement.",
      ja: "基本的な請求詳細と支払い条件を含むクリーンでミニマルな請求書レイアウト。",
      ko: "기본 청구 세부 정보와 결제 조건이 포함된 깔끔하고 미니멀한 청구서 레이아웃.",
      pt: "Um layout de fatura limpo e minimalista com detalhes de cobrança essenciais e termos de pagamento.",
      "zh-CN": "简洁的发票布局，包含基本账单详情和付款条款。",
    }),
    minimalInvoiceEyebrow: t({
      en: "Invoice #INV-2026-042",
      es: "Factura #INV-2026-042",
      fr: "Facture #INV-2026-042",
      ja: "請求書 #INV-2026-042",
      ko: "청구서 #INV-2026-042",
      pt: "Fatura #INV-2026-042",
      "zh-CN": "发票 #INV-2026-042",
    }),
    minimalInvoiceHeading: t({
      en: "Simple, clean, professional.",
      es: "Simple, limpio, profesional.",
      fr: "Simple, propre, professionnel.",
      ja: "シンプル、クリーン、プロフェッショナル。",
      ko: "단순하고 깔끔하며 전문적입니다.",
      pt: "Simples, limpo, profissional.",
      "zh-CN": "简洁、干净、专业。",
    }),
    minimalInvoiceName: t({
      en: "Minimal invoice",
      es: "Factura minimalista",
      fr: "Facture minimale",
      ja: "ミニマル請求書",
      ko: "미니멀 청구서",
      pt: "Fatura minimalista",
      "zh-CN": "极简发票",
    }),
    pageFooterDescription: t({
      en: "A compact document footer with page numbers, legal text, and brand marks.",
      es: "Un pie de página compacto con números de página, texto legal y marcas de marca.",
      fr: "Un pied de page compact avec numéros de page, texte légal et marques de fabrique.",
      ja: "ページ番号、法的テキスト、ブランドマークを含むコンパクトなドキュメントフッター。",
      ko: "페이지 번호, 법적 텍스트 및 브랜드 마크가 포함된 компак트한 문서 푸터.",
      pt: "Um rodapé compacto com números de página, texto legal e marcas da marca.",
      "zh-CN": "包含页码、法律文本和品牌标识的紧凑文档页脚。",
    }),
    pageHeaderDescription: t({
      en: "A branded document header with logo, company details, and document title.",
      es: "Un encabezado de documento con marca, logo, detalles de la empresa y título del documento.",
      fr: "Un en-tête de document de marque avec logo, coordonnées de l'entreprise et titre du document.",
      ja: "ロゴ、会社情報、ドキュメントタイトルを含むブランド化されたドキュメントヘッダー。",
      ko: "로고, 회사 정보 및 문서 제목이 있는 브랜드 문서 헤더.",
      pt: "Um cabeçalho de documento com marca, logotipo, detalhes da empresa e título do documento.",
      "zh-CN": "带有徽标、公司详情和文档标题的品牌文档页眉。",
    }),
    sectionDescription: t({
      en: "A grouped content section with optional title, padding, and background.",
      es: "Una sección de contenido agrupada con título, relleno y fondo opcionales.",
      fr: "Une section de contenu groupée avec titre, marge intérieure et arrière-plan facultatifs.",
      ja: "オプションのタイトル、パディング、背景を含むグループ化されたコンテンツセクション。",
      ko: "선택적 제목, 패딩 및 배경이 있는 그룹화된 콘텐츠 섹션.",
      pt: "Uma seção de conteúdo agrupada com título, preenchimento e fundo opcionais.",
      "zh-CN": "带有可选标题、内边距和背景的分组内容部分。",
    }),
    signatureDescription: t({
      en: "A signature block for authorized signatories and approval lines.",
      es: "Un bloque de firma para firmantes autorizados y líneas de aprobación.",
      fr: "Un bloc de signature pour les signataires autorisés et les lignes d'approbation.",
      ja: "承認署名者と承認ラインのための署名ブロック。",
      ko: "인가된 서명자 및 승인 라인을 위한 서명 블록.",
      pt: "Um bloco de assinatura para signatários autorizados e linhas de aprovação.",
      "zh-CN": "用于授权签字人和审批行的签名块。",
    }),
    tableDescription: t({
      en: "A structured data table with headers, rows, and responsive column widths.",
      es: "Una tabla de datos estructurada con encabezados, filas y anchos de columna responsivos.",
      fr: "Un tableau de données structuré avec en-têtes, lignes et largeurs de colonnes réactives.",
      ja: "ヘッダー、行、レスポンシブ列幅を備えた構造化データテーブル.",
      ko: "헤더, 행 및 반응형 열 너비가 있는 구조화된 데이터 테이블.",
      pt: "Uma tabela de dados estruturada com cabeçalhos, linhas e larguras de coluna responsivas.",
      "zh-CN": "具有标题、行和响应式列宽的结构化数据表。",
    }),
    textDescription: t({
      en: "A versatile text component for headings, paragraphs, and inline content.",
      es: "Un componente de texto versátil para encabezados, párrafos y contenido en línea.",
      fr: "Un composant de texte polyvalent pour les titres, paragraphes et contenu en ligne.",
      ja: "見出し、段落、インラインコンテンツのための多用途テキストコンポーネント。",
      ko: "제목, 단락 및 인라인 콘텐츠를 위한 다용도 텍스트 컴포넌트.",
      pt: "Um componente de texto versátil para títulos, parágrafos e conteúdo em linha.",
      "zh-CN": "用于标题、段落和内联内容的多功能文本组件。",
    }),
  },
  key: "home-pdf-preview",
} satisfies Dictionary;

export default homePdfPreviewContent;
