import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const homePdfShowcaseContent = {
  content: {
    chooseBase: t({
      en: "Choose base",
      es: "Elegir base",
      fr: "Choisir la base",
      ja: "ベースを選択",
      ko: "베이스 선택",
      pt: "Escolher base",
      "zh-CN": "选择基础",
    }),
    chooseTemplate: t({
      en: "Choose template",
      es: "Elegir plantilla",
      fr: "Choisir le modèle",
      ja: "テンプレートを選択",
      ko: "템플릿 선택",
      pt: "Escolher modelo",
      "zh-CN": "选择模板",
    }),
    code: t({
      en: "Code",
      es: "Código",
      fr: "Code",
      ja: "コード",
      ko: "코드",
      pt: "Código",
      "zh-CN": "代码",
    }),
    componentsInDoc: t({
      en: "Components used in the selected document",
      es: "Componentes utilizados en el documento seleccionado",
      fr: "Composants utilisés dans le document sélectionné",
      ja: "選択されたドキュメントで使用されたコンポーネント",
      ko: "선택된 문서에서 사용된 컴포넌트",
      pt: "Componentes utilizados no documento selecionado",
      "zh-CN": "所选文档中使用的组件",
    }),
    componentsUsed: t({
      en: "Components Used",
      es: "Componentes utilizados",
      fr: "Composants utilisés",
      ja: "使用されたコンポーネント",
      ko: "사용된 컴포넌트",
      pt: "Componentes utilizados",
      "zh-CN": "使用的组件",
    }),
    documents: t({
      en: "Documents",
      es: "Documentos",
      fr: "Documents",
      ja: "ドキュメント",
      ko: "문서",
      pt: "Documentos",
      "zh-CN": "文档",
    }),
    pdfBase: t({
      en: "PDF base",
      es: "Base PDF",
      fr: "Base PDF",
      ja: "PDF ベース",
      ko: "PDF 베이스",
      pt: "Base PDF",
      "zh-CN": "PDF 基础",
    }),
    pdfExamples: t({
      en: "PDF examples",
      es: "Ejemplos de PDF",
      fr: "Exemples de PDF",
      ja: "PDF サンプル",
      ko: "PDF 예제",
      pt: "Exemplos de PDF",
      "zh-CN": "PDF 示例",
    }),
    preview: t({
      en: "Preview",
      es: "Vista previa",
      fr: "Aperçu",
      ja: "プレビュー",
      ko: "미리보기",
      pt: "Pré-visualização",
      "zh-CN": "预览",
    }),
    renderingCode: t({
      en: "Rendering code…",
      es: "Renderizando código…",
      fr: "Rendu du code en cours…",
      ja: "コードをレンダリング中…",
      ko: "코드 렌더링 중…",
      pt: "Renderizando código…",
      "zh-CN": "渲染代码中…",
    }),
  },
  key: "home-pdf-showcase",
} satisfies Dictionary;

export default homePdfShowcaseContent;
