import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const outputPanelContent = {
  content: {
    attachments: t({
      en: "Attachments",
      es: "Adjuntos",
      fr: "Pièces jointes",
      ja: "添付ファイル",
      ko: "첨부 파일",
      pt: "Anexos",
      "zh-CN": "附件",
    }),
    authors: t({
      en: "Authors",
      es: "Autores",
      fr: "Auteurs",
      ja: "著者",
      ko: "저자",
      pt: "Autores",
      "zh-CN": "作者",
    }),
    bookmarks: t({
      en: "Bookmarks",
      es: "Marcadores",
      fr: "Signets",
      ja: "ブックマーク",
      ko: "북마크",
      pt: "Marcadores",
      "zh-CN": "书签",
    }),
    created: t({
      en: "Created",
      es: "Creado",
      fr: "Créé",
      ja: "作成日",
      ko: "생성일",
      pt: "Criado",
      "zh-CN": "创建时间",
    }),
    loadingWasm: t({
      en: "loading wasm…",
      es: "cargando wasm…",
      fr: "chargement de wasm…",
      ja: "wasm を読み込み中…",
      ko: "wasm 로딩 중…",
      pt: "carregando wasm…",
      "zh-CN": "加载 wasm 中…",
    }),
    no: t({
      en: "no",
      es: "no",
      fr: "non",
      ja: "いいえ",
      ko: "아니요",
      pt: "não",
      "zh-CN": "否",
    }),
    none: t({
      en: "none",
      es: "ninguno",
      fr: "aucun",
      ja: "なし",
      ko: "없음",
      pt: "nenhum",
      "zh-CN": "无",
    }),
    openPdfInNewTab: t({
      en: "Open PDF in new tab",
      es: "Abrir PDF en nueva pestaña",
      fr: "Ouvrir le PDF dans un nouvel onglet",
      ja: "PDF を新しいタブで開く",
      ko: "새 탭에서 PDF 열기",
      pt: "Abrir PDF em nova aba",
      "zh-CN": "在新标签页中打开 PDF",
    }),
    pages: t({
      en: "Pages",
      es: "Páginas",
      fr: "Pages",
      ja: "ページ",
      ko: "페이지",
      pt: "Páginas",
      "zh-CN": "页数",
    }),
    plainPdf: t({
      en: "plain PDF",
      es: "PDF simple",
      fr: "PDF standard",
      ja: "プレーン PDF",
      ko: "일반 PDF",
      pt: "PDF simples",
      "zh-CN": "普通 PDF",
    }),
    renderedOutput: t({
      en: "Rendered output",
      es: "Salida renderizada",
      fr: "Sortie rendue",
      ja: "レンダリングされた出力",
      ko: "렌더링된 출력",
      pt: "Saída renderizada",
      "zh-CN": "渲染输出",
    }),
    renderedPdf: t({
      en: "Rendered PDF",
      es: "PDF renderizado",
      fr: "PDF rendu",
      ja: "レンダリングされた PDF",
      ko: "렌더링된 PDF",
      pt: "PDF renderizado",
      "zh-CN": "渲染的 PDF",
    }),
    rendering: t({
      en: "rendering…",
      es: "renderizando…",
      fr: "rendu en cours…",
      ja: "レンダリング中…",
      ko: "렌더링 중…",
      pt: "renderizando…",
      "zh-CN": "渲染中…",
    }),
    standards: t({
      en: "Standards",
      es: "Estándares",
      fr: "Standards",
      ja: "標準",
      ko: "표준",
      pt: "Padrões",
      "zh-CN": "标准",
    }),
    tagged: t({
      en: "Tagged",
      es: "Etiquetado",
      fr: "Balisé",
      ja: "タグ付き",
      ko: "태그됨",
      pt: "Marcado",
      "zh-CN": "已标记",
    }),
    title: t({
      en: "Title",
      es: "Título",
      fr: "Titre",
      ja: "タイトル",
      ko: "제목",
      pt: "Título",
      "zh-CN": "标题",
    }),
    yes: t({
      en: "yes",
      es: "sí",
      fr: "oui",
      ja: "はい",
      ko: "예",
      pt: "sim",
      "zh-CN": "是",
    }),
  },
  key: "output-panel",
} satisfies Dictionary;

export default outputPanelContent;
