import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const themeBuilderContent = {
  content: {
    changesRenderAutomatically: t({
      en: "Changes render in the preview automatically.",
      es: "Los cambios se renderizan en la vista previa automáticamente.",
      fr: "Les modifications s'affichent automatiquement dans l'aperçu.",
      ja: "変更は自動的にプレビューにレンダリングされます。",
      ko: "변경 사항이 미리보기에 자동으로 렌더링됩니다.",
      pt: "As alterações são renderizadas na pré-visualização automaticamente.",
      "zh-CN": "更改会自动在预览中渲染。",
    }),
    code: t({
      en: "Code",
      es: "Código",
      fr: "Code",
      ja: "コード",
      ko: "코드",
      pt: "Código",
      "zh-CN": "代码",
    }),
    couldNotCopyShareLink: t({
      en: "Could not copy the share link",
      es: "No se pudo copiar el enlace para compartir",
      fr: "Impossible de copier le lien de partage",
      ja: "共有リンクをコピーできませんでした",
      ko: "공유 링크를 복사할 수 없습니다",
      pt: "Não foi possível copiar o link de compartilhamento",
      "zh-CN": "无法复制分享链接",
    }),
    customize: t({
      en: "Customize",
      es: "Personalizar",
      fr: "Personnaliser",
      ja: "カスタマイズ",
      ko: "사용자 정의",
      pt: "Personalizar",
      "zh-CN": "自定义",
    }),
    customizeTheme: t({
      en: "Customize theme",
      es: "Personalizar tema",
      fr: "Personnaliser le thème",
      ja: "テーマをカスタマイズ",
      ko: "테마 사용자 정의",
      pt: "Personalizar tema",
      "zh-CN": "自定义主题",
    }),
    download: t({
      en: "Download",
      es: "Descargar",
      fr: "Télécharger",
      ja: "ダウンロード",
      ko: "다운로드",
      pt: "Baixar",
      "zh-CN": "下载",
    }),
    downloadPdfTooltip: t({
      en: "Download PDF",
      es: "Descargar PDF",
      fr: "Télécharger le PDF",
      ja: "PDF をダウンロード",
      ko: "PDF 다운로드",
      pt: "Baixar PDF",
      "zh-CN": "下载 PDF",
    }),
    getCodeTooltip: t({
      en: "Get theme code",
      es: "Obtener código del tema",
      fr: "Obtenir le code du thème",
      ja: "テーマコードを取得",
      ko: "테마 코드 가져오기",
      pt: "Obter código do tema",
      "zh-CN": "获取主题代码",
    }),
    livePdfPreview: t({
      en: "Live PDF preview",
      es: "Vista previa PDF en vivo",
      fr: "Aperçu PDF en direct",
      ja: "ライブ PDF プレビュー",
      ko: "실시간 PDF 미리보기",
      pt: "Pré-visualização PDF ao vivo",
      "zh-CN": "实时 PDF 预览",
    }),
    open: t({
      en: "Open",
      es: "Abrir",
      fr: "Ouvrir",
      ja: "開く",
      ko: "열기",
      pt: "Abrir",
      "zh-CN": "打开",
    }),
    openPdfTooltip: t({
      en: "Open PDF in new tab",
      es: "Abrir PDF en nueva pestaña",
      fr: "Ouvrir le PDF dans un nouvel onglet",
      ja: "PDF を新しいタブで開く",
      ko: "새 탭에서 PDF 열기",
      pt: "Abrir PDF em nova aba",
      "zh-CN": "在新标签页中打开 PDF",
    }),
    pdfRendererBase: t({
      en: "PDF renderer base",
      es: "Base del renderizador PDF",
      fr: "Base du rendu PDF",
      ja: "PDF レンダラーベース",
      ko: "PDF 렌더러 베이스",
      pt: "Base do renderizador PDF",
      "zh-CN": "PDF 渲染器基础",
    }),
    redo: t({
      en: "Redo (⌘⇧Z)",
      es: "Rehacer (⌘⇧Z)",
      fr: "Rétablir (⌘⇧Z)",
      ja: "やり直し (⌘⇧Z)",
      ko: "다시 실행 (⌘⇧Z)",
      pt: "Refazer (⌘⇧Z)",
      "zh-CN": "重做 (⌘⇧Z)",
    }),
    reset: t({
      en: "Reset",
      es: "Restablecer",
      fr: "Réinitialiser",
      ja: "リセット",
      ko: "초기화",
      pt: "Redefinir",
      "zh-CN": "重置",
    }),
    resetTooltip: t({
      en: "Reset to preset defaults",
      es: "Restablecer valores predeterminados",
      fr: "Réinitialiser aux valeurs par défaut",
      ja: "プリセットのデフォルトにリセット",
      ko: "프리셋 기본값으로 초기화",
      pt: "Redefinir para os padrões predefinidos",
      "zh-CN": "重置为预设默认值",
    }),
    share: t({
      en: "Share",
      es: "Compartir",
      fr: "Partager",
      ja: "共有",
      ko: "공유",
      pt: "Compartilhar",
      "zh-CN": "分享",
    }),
    shareLinkCopied: t({
      en: "Share link copied",
      es: "Enlace de compartir copiado",
      fr: "Lien de partage copié",
      ja: "共有リンクをコピーしました",
      ko: "공유 링크가 복사되었습니다",
      pt: "Link de compartilhamento copiado",
      "zh-CN": "分享链接已复制",
    }),
    shareTooltip: t({
      en: "Share theme",
      es: "Compartir tema",
      fr: "Partager le thème",
      ja: "テーマを共有",
      ko: "테마 공유",
      pt: "Compartilhar tema",
      "zh-CN": "分享主题",
    }),
    themeControls: t({
      en: "Theme controls",
      es: "Controles del tema",
      fr: "Contrôles du thème",
      ja: "テーマコントロール",
      ko: "테마 컨트롤",
      pt: "Controles do tema",
      "zh-CN": "主题控制",
    }),
    undo: t({
      en: "Undo (⌘Z)",
      es: "Deshacer (⌘Z)",
      fr: "Annuler (⌘Z)",
      ja: "元に戻す (⌘Z)",
      ko: "실행 취소 (⌘Z)",
      pt: "Desfazer (⌘Z)",
      "zh-CN": "撤销 (⌘Z)",
    }),
  },
  key: "theme-builder",
} satisfies Dictionary;

export default themeBuilderContent;
