import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const themeControlsContent = {
  content: {
    accent: t({
      en: "Accent",
      es: "Acento",
      fr: "Accent",
      ja: "アクセント",
      ko: "강조",
      pt: "Destaque",
      "zh-CN": "强调色",
    }),
    accentDescription: t({
      en: "Links, highlights",
      es: "Enlaces, resaltados",
      fr: "Liens, mises en surbrillance",
      ja: "リンク、ハイライト",
      ko: "링크, 강조",
      pt: "Links, destaques",
      "zh-CN": "链接、高亮",
    }),
    background: t({
      en: "Background",
      es: "Fondo",
      fr: "Arrière-plan",
      ja: "バックグラウンド",
      ko: "배경",
      pt: "Fundo",
      "zh-CN": "背景",
    }),
    backgroundDescription: t({
      en: "Page background",
      es: "Fondo de página",
      fr: "Arrière-plan de la page",
      ja: "ページ背景",
      ko: "페이지 배경",
      pt: "Fundo da página",
      "zh-CN": "页面背景",
    }),
    body: t({
      en: "Body",
      es: "Cuerpo",
      fr: "Corps",
      ja: "本文",
      ko: "본문",
      pt: "Corpo",
      "zh-CN": "正文",
    }),
    bodyDescription: t({
      en: "Base type used across paragraphs and tables.",
      es: "Tipo base utilizado en párrafos y tablas.",
      fr: "Police de base utilisée dans les paragraphes et les tableaux.",
      ja: "段落やテーブル全体で使用される基本フォント。",
      ko: "단락과 테이블 전체에서 사용되는 기본 글꼴.",
      pt: "Fonte base usada em parágrafos e tabelas.",
      "zh-CN": "段落和表格中使用的基础字体。",
    }),
    border: t({
      en: "Border",
      es: "Borde",
      fr: "Bordure",
      ja: "ボーダー",
      ko: "테두리",
      pt: "Borda",
      "zh-CN": "边框",
    }),
    borderDescription: t({
      en: "Dividers, table lines",
      es: "Divisores, líneas de tabla",
      fr: "Séparateurs, lignes de tableau",
      ja: "区切り線、テーブル線",
      ko: "구분선, 테이블 선",
      pt: "Separadores, linhas de tabela",
      "zh-CN": "分隔线、表格线",
    }),
    bottom: t({
      en: "Bottom",
      es: "Inferior",
      fr: "Bas",
      ja: "下",
      ko: "아래",
      pt: "Inferior",
      "zh-CN": "底部",
    }),
    colors: t({
      en: "Colors",
      es: "Colores",
      fr: "Couleurs",
      ja: "カラー",
      ko: "색상",
      pt: "Cores",
      "zh-CN": "颜色",
    }),
    components: t({
      en: "Components",
      es: "Componentes",
      fr: "Composants",
      ja: "コンポーネント",
      ko: "컴포넌트",
      pt: "Componentes",
      "zh-CN": "组件",
    }),
    destructive: t({
      en: "Destructive",
      es: "Destruktivo",
      fr: "Destructif",
      ja: "ディストラクティブ",
      ko: "파괴적",
      pt: "Destrutivo",
      "zh-CN": "破坏性",
    }),
    destructiveDescription: t({
      en: "Errors",
      es: "Errores",
      fr: "Erreurs",
      ja: "エラー",
      ko: "오류",
      pt: "Erros",
      "zh-CN": "错误",
    }),
    exportName: t({
      en: "Export name",
      es: "Nombre de exportación",
      fr: "Nom d'exportation",
      ja: "エクスポート名",
      ko: "내보내기 이름",
      pt: "Nome de exportação",
      "zh-CN": "导出名称",
    }),
    fontFamily: t({
      en: "Font family",
      es: "Familia de fuentes",
      fr: "Famille de polices",
      ja: "フォントファミリー",
      ko: "글꼴 패밀리",
      pt: "Família de fontes",
      "zh-CN": "字体族",
    }),
    fontSize: t({
      en: "Font size",
      es: "Tamaño de fuente",
      fr: "Taille de police",
      ja: "フォントサイズ",
      ko: "글꼴 크기",
      pt: "Tamanho da fonte",
      "zh-CN": "字体大小",
    }),
    foreground: t({
      en: "Foreground",
      es: "Primer plano",
      fr: "Premier plan",
      ja: "フォアグラウンド",
      ko: "전경",
      pt: "Primeiro plano",
      "zh-CN": "前景",
    }),
    headings: t({
      en: "Headings",
      es: "Encabezados",
      fr: "Titres",
      ja: "見出し",
      ko: "제목",
      pt: "Títulos",
      "zh-CN": "标题",
    }),
    headingsDescription: t({
      en: "Display type, weight, and scale.",
      es: "Tipo de visualización, peso y escala.",
      fr: "Police d'affichage, graisse et échelle.",
      ja: "表示タイプ、ウェイト、スケール。",
      ko: "표시 유형, 굵기 및 크기.",
      pt: "Tipo de exibição, peso e escala.",
      "zh-CN": "显示类型、字重和缩放。",
    }),
    info: t({
      en: "Info",
      es: "Info",
      fr: "Info",
      ja: "情報",
      ko: "정보",
      pt: "Info",
      "zh-CN": "信息",
    }),
    infoDescription: t({
      en: "Info states",
      es: "Estados de información",
      fr: "États d'information",
      ja: "情報状態",
      ko: "정보 상태",
      pt: "Estados de informação",
      "zh-CN": "信息状态",
    }),
    landscape: t({
      en: "Landscape",
      es: "Horizontal",
      fr: "Paysage",
      ja: "横向き",
      ko: "가로",
      pt: "Paisagem",
      "zh-CN": "横向",
    }),
    layout: t({
      en: "Layout",
      es: "Diseño",
      fr: "Agencement",
      ja: "レイアウト",
      ko: "레이아웃",
      pt: "Layout",
      "zh-CN": "布局",
    }),
    left: t({
      en: "Left",
      es: "Izquierda",
      fr: "Gauche",
      ja: "左",
      ko: "왼쪽",
      pt: "Esquerda",
      "zh-CN": "左侧",
    }),
    lineHeight: t({
      en: "Line height",
      es: "Altura de línea",
      fr: "Interligne",
      ja: "行の高さ",
      ko: "행 높이",
      pt: "Altura da linha",
      "zh-CN": "行高",
    }),
    margins: t({
      en: "Margins",
      es: "Márgenes",
      fr: "Marges",
      ja: "マージン",
      ko: "여백",
      pt: "Margens",
      "zh-CN": "边距",
    }),
    marginsDescription: t({
      en: "Space between content and every page edge.",
      es: "Espacio entre el contenido y cada borde de la página.",
      fr: "Espace entre le contenu et chaque bord de la page.",
      ja: "コンテンツとページの端の間のスペース。",
      ko: "콘텐츠와 페이지 가장자리 사이의 공간.",
      pt: "Espaço entre o conteúdo e cada borda da página.",
      "zh-CN": "内容与页面边缘之间的空间。",
    }),
    muted: t({
      en: "Muted",
      es: "Atenuado",
      fr: "Estompé",
      ja: "ミュート",
      ko: "뮤트",
      pt: "Suavizado",
      "zh-CN": "柔和色",
    }),
    mutedDescription: t({
      en: "Secondary fill",
      es: "Relleno secundario",
      fr: "Remplissage secondaire",
      ja: "セカンダリフィル",
      ko: "보조 채우기",
      pt: "Preenchimento secundário",
      "zh-CN": "次要填充",
    }),
    mutedFgDescription: t({
      en: "Captions, footnotes",
      es: "Subtítulos, notas al pie",
      fr: "Légendes, notes de bas de page",
      ja: "キャプション、脚注",
      ko: "캡션, 각주",
      pt: "Legendas, notas de rodapé",
      "zh-CN": "说明文字、脚注",
    }),
    mutedForeground: t({
      en: "Muted foreground",
      es: "Primer plano atenuado",
      fr: "Premier plan estompé",
      ja: "ミュートフォアグラウンド",
      ko: "뮤트 전경",
      pt: "Primeiro plano suavizado",
      "zh-CN": "柔和色前景",
    }),
    orientation: t({
      en: "Orientation",
      es: "Orientación",
      fr: "Orientation",
      ja: "向き",
      ko: "방향",
      pt: "Orientação",
      "zh-CN": "方向",
    }),
    page: t({
      en: "Page",
      es: "Página",
      fr: "Page",
      ja: "ページ",
      ko: "페이지",
      pt: "Página",
      "zh-CN": "页面",
    }),
    pageDescription: t({
      en: "Paper format and reading direction.",
      es: "Formato de papel y dirección de lectura.",
      fr: "Format de papier et direction de lecture.",
      ja: "用紙フォーマットと読み取り方向。",
      ko: "용지 형식 및 읽기 방향.",
      pt: "Formato de papel e direção de leitura.",
      "zh-CN": "纸张格式和阅读方向。",
    }),
    paragraphs: t({
      en: "Paragraphs",
      es: "Párrafos",
      fr: "Paragraphes",
      ja: "段落",
      ko: "단락",
      pt: "Parágrafos",
      "zh-CN": "段落",
    }),
    portrait: t({
      en: "Portrait",
      es: "Vertical",
      fr: "Portrait",
      ja: "縦向き",
      ko: "세로",
      pt: "Retrato",
      "zh-CN": "纵向",
    }),
    primary: t({
      en: "Primary",
      es: "Primario",
      fr: "Primaire",
      ja: "プライマリ",
      ko: "주요",
      pt: "Primário",
      "zh-CN": "主色",
    }),
    primaryBgDescription: t({
      en: "Brand emphasis",
      es: "Énfasis de marca",
      fr: "Mise en valeur de la marque",
      ja: "ブランド強調",
      ko: "브랜드 강조",
      pt: "Ênfase da marca",
      "zh-CN": "品牌强调",
    }),
    primaryDescription: t({
      en: "Primary text",
      es: "Texto primario",
      fr: "Texte primaire",
      ja: "プライマリテキスト",
      ko: "주요 텍스트",
      pt: "Texto primário",
      "zh-CN": "主文本",
    }),
    primaryFgDescription: t({
      en: "Text on primary",
      es: "Texto sobre primario",
      fr: "Texte sur primaire",
      ja: "プライマリ上のテキスト",
      ko: "주요색상 위의 텍스트",
      pt: "Texto sobre primário",
      "zh-CN": "主色上的文本",
    }),
    primaryForeground: t({
      en: "Primary foreground",
      es: "Primer plano primario",
      fr: "Premier plan primaire",
      ja: "プライマリフォアグラウンド",
      ko: "주요 전경",
      pt: "Primeiro plano primário",
      "zh-CN": "主色前景",
    }),
    randomPreset: t({
      en: "Random preset",
      es: "Preselección aleatoria",
      fr: "Préréglage aléatoire",
      ja: "ランダムプリセット",
      ko: "무작위 프리셋",
      pt: "Predefinição aleatória",
      "zh-CN": "随机预设",
    }),
    rhythm: t({
      en: "Rhythm",
      es: "Ritmo",
      fr: "Rythme",
      ja: "リズム",
      ko: "리듬",
      pt: "Ritmo",
      "zh-CN": "节奏",
    }),
    rhythmDescription: t({
      en: "Vertical spacing between document elements.",
      es: "Espaciado vertical entre elementos del documento.",
      fr: "Espacement vertical entre les éléments du document.",
      ja: "ドキュメント要素間の垂直スペース。",
      ko: "문서 요소 사이의 수직 간격.",
      pt: "Espaçamento vertical entre elementos do documento.",
      "zh-CN": "文档元素之间的垂直间距。",
    }),
    right: t({
      en: "Right",
      es: "Derecha",
      fr: "Droite",
      ja: "右",
      ko: "오른쪽",
      pt: "Direita",
      "zh-CN": "右侧",
    }),
    sections: t({
      en: "Sections",
      es: "Secciones",
      fr: "Sections",
      ja: "セクション",
      ko: "섹션",
      pt: "Seções",
      "zh-CN": "章节",
    }),
    size: t({
      en: "Size",
      es: "Tamaño",
      fr: "Taille",
      ja: "サイズ",
      ko: "크기",
      pt: "Tamanho",
      "zh-CN": "尺寸",
    }),
    success: t({
      en: "Success",
      es: "Éxito",
      fr: "Succès",
      ja: "成功",
      ko: "성공",
      pt: "Sucesso",
      "zh-CN": "成功",
    }),
    successDescription: t({
      en: "Success states",
      es: "Estados de éxito",
      fr: "États de succès",
      ja: "成功状態",
      ko: "성공 상태",
      pt: "Estados de sucesso",
      "zh-CN": "成功状态",
    }),
    top: t({
      en: "Top",
      es: "Superior",
      fr: "Haut",
      ja: "上",
      ko: "위",
      pt: "Topo",
      "zh-CN": "顶部",
    }),
    typography: t({
      en: "Typography",
      es: "Tipografía",
      fr: "Typographie",
      ja: "タイポグラフィ",
      ko: "타이포그래피",
      pt: "Tipografia",
      "zh-CN": "排版",
    }),
    warning: t({
      en: "Warning",
      es: "Advertencia",
      fr: "Avertissement",
      ja: "警告",
      ko: "경고",
      pt: "Aviso",
      "zh-CN": "警告",
    }),
    warningDescription: t({
      en: "Warning states",
      es: "Estados de advertencia",
      fr: "États d'avertissement",
      ja: "警告状態",
      ko: "경고 상태",
      pt: "Estados de aviso",
      "zh-CN": "警告状态",
    }),
    weight: t({
      en: "Weight",
      es: "Peso",
      fr: "Graisse",
      ja: "ウェイト",
      ko: "굵기",
      pt: "Peso",
      "zh-CN": "字重",
    }),
  },
  key: "theme-controls",
} satisfies Dictionary;

export default themeControlsContent;
