import { t } from "intlayer";
import type { Dictionary } from "intlayer";

const themeCodeDialogContent = {
  content: {
    copied: t({
      en: "Copied",
      es: "Copiado",
      fr: "Copié",
      ja: "コピーしました",
      ko: "복사됨",
      pt: "Copiado",
      "zh-CN": "已复制",
    }),
    copy: t({
      en: "Copy",
      es: "Copiar",
      fr: "Copier",
      ja: "コピー",
      ko: "복사",
      pt: "Copiar",
      "zh-CN": "复制",
    }),
    copyInto: t({
      en: "Copy into",
      es: "Copiar en",
      fr: "Copier dans",
      ja: "コピー先",
      ko: "복사 대상",
      pt: "Copiar para",
      "zh-CN": "复制到",
    }),
    couldNotCopyThemeCode: t({
      en: "Could not copy theme code",
      es: "No se pudo copiar el código del tema",
      fr: "Impossible de copier le code du thème",
      ja: "テーマコードをコピーできませんでした",
      ko: "테마 코드를 복사할 수 없습니다",
      pt: "Não foi possível copiar o código do tema",
      "zh-CN": "无法复制主题代码",
    }),
    deltaFrom: t({
      en: "Delta from",
      es: "Delta de",
      fr: "Delta de",
      ja: "デルタ元",
      ko: "델타 소스",
      pt: "Delta de",
      "zh-CN": "差异来自",
    }),
    deltaTip: t({
      en: "use the Delta tab if you only changed a few values — it shows a minimal override to merge with your base preset.",
      es: "use la pestaña Delta si solo cambió algunos valores — muestra una sobreescritura mínima para fusionar con su preselección base.",
      fr: "utilisez l'onglet Delta si vous n'avez modifié que quelques valeurs — il affiche une surcharge minimale à fusionner avec votre préréglage de base.",
      ja: "いくつかの値のみを変更した場合は Delta タブを使用してください — ベースプリセットとマージする最小限のオーバーライドを表示します。",
      ko: "몇 가지 값만 변경한 경우 Delta 탭을 사용하세요 — 기본 프리셋과 병합할 최소한의 재정의를 보여줍니다.",
      pt: "use a aba Delta se você alterou apenas alguns valores — ela exibe uma substituição mínima para mesclar com sua predefinição base.",
      "zh-CN":
        "如果只更改了几个值，请使用 Delta 选项卡——它显示与基础预设合并的最小覆盖。",
    }),
    downloadTs: t({
      en: "Download .ts",
      es: "Descargar .ts",
      fr: "Télécharger .ts",
      ja: "ダウンロード .ts",
      ko: "다운로드 .ts",
      pt: "Baixar .ts",
      "zh-CN": "下载 .ts",
    }),
    fullTheme: t({
      en: "Full theme",
      es: "Tema completo",
      fr: "Thème complet",
      ja: "フルテーマ",
      ko: "전체 테마",
      pt: "Tema completo",
      "zh-CN": "完整主题",
    }),
    generatedThemeCode: t({
      en: "Generated theme code",
      es: "Código del tema generado",
      fr: "Code du thème généré",
      ja: "生成されたテーマコード",
      ko: "생성된 테마 코드",
      pt: "Código do tema gerado",
      "zh-CN": "生成的主题代码",
    }),
    inYourProjectAndPassItToAnyThemedPdfcnDocument: t({
      en: "in your project and pass it to any themed pdfcn document.",
      es: "en su proyecto y páselo a cualquier documento pdfcn con tema.",
      fr: "dans votre projet et passez-le à tout document pdfcn thémé.",
      ja: "プロジェクトにコピーし、テーマ付き pdfcn ドキュメントに渡します。",
      ko: "프로젝트에 복사하고 테마가 적용된 pdfcn 문서에 전달합니다.",
      pt: "no seu projeto e passe-o para qualquer documento pdfcn com tema.",
      "zh-CN": "到您的项目中，并传递给任何主题化的 pdfcn 文档。",
    }),
    productionNote: t({
      en: "Production note:",
      es: "Nota de producción:",
      fr: "Note de production :",
      ja: "本番環境の注意：",
      ko: "프로덕션 참고사항:",
      pt: "Nota de produção:",
      "zh-CN": "生产说明：",
    }),
    productionNoteDescription: t({
      en: "this theme uses fonts from jsDelivr at runtime. For offline or restricted deployments, self-host those font files or switch to built-in fonts before release.",
      es: "este tema usa fuentes de jsDespacho en tiempo de ejecución. Para implementaciones sin conexión o restringidas, aloje esas fuentes o cambie a fuentes integradas antes del lanzamiento.",
      fr: "ce thème utilise des polices de jsDelivr au moment de l'exécution. Pour les déploiements hors ligne ou restreints, auto-hébergez ces fichiers de polices ou passez aux polices intégrées avant la publication.",
      ja: "このテーマは実行時に jsDelivr のフォントを使用します。オフラインまたは制限されたデプロイメントの場合は、リリ前にそのフォントファイルをセルフホスティングするか、組み込みフォントに切り替えてください。",
      ko: "이 테마는 런타임에 jsDelivr의 글꼴을 사용합니다. 오프라인 또는 제한된 배포의 경우 배포 전에 해당 글꼴 파일을 자체 호스팅하거나 내장 글꼴로 전환하세요.",
      pt: "este tema usa fontes do jsDelivr em tempo de execução. Para implantações offline ou restritas, hospede essas fontes ou mude para fontes integradas antes do lançamento.",
      "zh-CN":
        "此主题在运行时使用来自 jsDelivr 的字体。对于离线或受限部署，请在发布前自托管这些字体文件或切换到内置字体。",
    }),
    themeCodeCopied: t({
      en: "Theme code copied",
      es: "Código del tema copiado",
      fr: "Code du thème copié",
      ja: "テーマコードをコピーしました",
      ko: "테마 코드가 복사되었습니다",
      pt: "Código do tema copiado",
      "zh-CN": "主题代码已复制",
    }),
    tip: t({
      en: "Tip:",
      es: "Consejo:",
      fr: "Astuce :",
      ja: "ヒント：",
      ko: "팁:",
      pt: "Dica:",
      "zh-CN": "提示：",
    }),
  },
  key: "theme-code-dialog",
} satisfies Dictionary;

export default themeCodeDialogContent;
